#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

TROPD_ONPOLICY_PATCH_DIR="${TROPD_ONPOLICY_PATCH_DIR:-$SCRIPT_DIR/tropd_onpolicy_patch}"
TROPD_ONPOLICY_VERL_DIR="${TROPD_ONPOLICY_VERL_DIR:-/workspace/opd1/verl}"
TROPD_ONPOLICY_VERBOSE="${TROPD_ONPOLICY_VERBOSE:-1}"
TROPD_TOP_K="${TROPD_TOP_K:-64}"
TROPD_FKL_COEF="${TROPD_FKL_COEF:-1.0}"
TROPD_REGION_MODE="${TROPD_REGION_MODE:-adaptive_trust_region}"
TROPD_TRUST_REGION_MODE="${TROPD_TRUST_REGION_MODE:-bernoulli}"
TROPD_TRUST_REGION_THRESHOLD="${TROPD_TRUST_REGION_THRESHOLD:-0.5}"
TROPD_OUTLIER_THRESHOLD="${TROPD_OUTLIER_THRESHOLD:-5.0}"
TROPD_OUTLIER_MODE="${TROPD_OUTLIER_MODE:-topk_fkl}"
TROPD_OFFPOLICY_ENABLE="${TROPD_OFFPOLICY_ENABLE:-1}"
TROPD_OFFPOLICY_BETA="${TROPD_OFFPOLICY_BETA:-1.0}"
TROPD_OFFPOLICY_MAX_PREFIX_LEN="${TROPD_OFFPOLICY_MAX_PREFIX_LEN:--1}"
TROPD_OFFPOLICY_ANNEAL="${TROPD_OFFPOLICY_ANNEAL:-cosine}"
TROPD_OFFPOLICY_ANNEAL_STEPS="${TROPD_OFFPOLICY_ANNEAL_STEPS:-0}"
TROPD_OFFPOLICY_STEP="${TROPD_OFFPOLICY_STEP:-0}"
TROPD_OFFPOLICY_TEACHER_DO_SAMPLE="${TROPD_OFFPOLICY_TEACHER_DO_SAMPLE:-1}"
TROPD_OFFPOLICY_TEACHER_TEMPERATURE="${TROPD_OFFPOLICY_TEACHER_TEMPERATURE:-1.0}"
TROPD_OFFPOLICY_TEACHER_TOP_P="${TROPD_OFFPOLICY_TEACHER_TOP_P:-1.0}"
TROPD_OFFPOLICY_TEACHER_TOP_K="${TROPD_OFFPOLICY_TEACHER_TOP_K:-0}"

export TROPD_ONPOLICY_ENABLE=1
export TROPD_ONPOLICY_PATCH_DIR
export TROPD_ONPOLICY_VERL_DIR
export TROPD_ONPOLICY_VERBOSE
export TROPD_TOP_K
export TROPD_FKL_COEF
export TROPD_REGION_MODE
export TROPD_TRUST_REGION_MODE
export TROPD_TRUST_REGION_THRESHOLD
export TROPD_OUTLIER_THRESHOLD
export TROPD_OUTLIER_MODE
export TROPD_OFFPOLICY_ENABLE
export TROPD_OFFPOLICY_BETA
export TROPD_OFFPOLICY_MAX_PREFIX_LEN
export TROPD_OFFPOLICY_ANNEAL
export TROPD_OFFPOLICY_ANNEAL_STEPS
export TROPD_OFFPOLICY_STEP
export TROPD_OFFPOLICY_TEACHER_DO_SAMPLE
export TROPD_OFFPOLICY_TEACHER_TEMPERATURE
export TROPD_OFFPOLICY_TEACHER_TOP_P
export TROPD_OFFPOLICY_TEACHER_TOP_K
export PYTHONPATH="$TROPD_ONPOLICY_PATCH_DIR:$TROPD_ONPOLICY_VERL_DIR:${PYTHONPATH:-}"

G_OPD_EXPERIMENT_NAME="${G_OPD_EXPERIMENT_NAME:-146_qwen3_1.7b_teacher_qwen3_4b_tropd}"
export G_OPD_EXPERIMENT_NAME

echo "[tropd-onpolicy] experiment=$G_OPD_EXPERIMENT_NAME"
echo "[tropd-onpolicy] patch_dir=$TROPD_ONPOLICY_PATCH_DIR"
echo "[tropd-onpolicy] top_k=$TROPD_TOP_K fkl_coef=$TROPD_FKL_COEF region_mode=$TROPD_REGION_MODE trust_mode=$TROPD_TRUST_REGION_MODE outlier_threshold=$TROPD_OUTLIER_THRESHOLD outlier_mode=$TROPD_OUTLIER_MODE"
echo "[tropd-onpolicy] offpolicy=$TROPD_OFFPOLICY_ENABLE beta=$TROPD_OFFPOLICY_BETA max_prefix_len=$TROPD_OFFPOLICY_MAX_PREFIX_LEN anneal=$TROPD_OFFPOLICY_ANNEAL anneal_steps=$TROPD_OFFPOLICY_ANNEAL_STEPS"
echo "[tropd-onpolicy] teacher_do_sample=$TROPD_OFFPOLICY_TEACHER_DO_SAMPLE teacher_temperature=$TROPD_OFFPOLICY_TEACHER_TEMPERATURE teacher_top_p=$TROPD_OFFPOLICY_TEACHER_TOP_P teacher_top_k=$TROPD_OFFPOLICY_TEACHER_TOP_K"

exec "$SCRIPT_DIR/run_qwen3-4b-g-opd.sh" \
        +ray_kwargs.ray_init.runtime_env.env_vars.PYTHONPATH="$PYTHONPATH" \
        +ray_kwargs.ray_init.runtime_env.env_vars.TROPD_ONPOLICY_ENABLE="$TROPD_ONPOLICY_ENABLE" \
        +ray_kwargs.ray_init.runtime_env.env_vars.TROPD_ONPOLICY_PATCH_DIR="$TROPD_ONPOLICY_PATCH_DIR" \
        +ray_kwargs.ray_init.runtime_env.env_vars.TROPD_ONPOLICY_VERL_DIR="$TROPD_ONPOLICY_VERL_DIR" \
        +ray_kwargs.ray_init.runtime_env.env_vars.TROPD_ONPOLICY_VERBOSE="$TROPD_ONPOLICY_VERBOSE" \
        +ray_kwargs.ray_init.runtime_env.env_vars.TROPD_TOP_K="$TROPD_TOP_K" \
        +ray_kwargs.ray_init.runtime_env.env_vars.TROPD_FKL_COEF="$TROPD_FKL_COEF" \
        +ray_kwargs.ray_init.runtime_env.env_vars.TROPD_REGION_MODE="$TROPD_REGION_MODE" \
        +ray_kwargs.ray_init.runtime_env.env_vars.TROPD_TRUST_REGION_MODE="$TROPD_TRUST_REGION_MODE" \
        +ray_kwargs.ray_init.runtime_env.env_vars.TROPD_TRUST_REGION_THRESHOLD="$TROPD_TRUST_REGION_THRESHOLD" \
        +ray_kwargs.ray_init.runtime_env.env_vars.TROPD_OUTLIER_THRESHOLD="$TROPD_OUTLIER_THRESHOLD" \
        +ray_kwargs.ray_init.runtime_env.env_vars.TROPD_OUTLIER_MODE="$TROPD_OUTLIER_MODE" \
        +ray_kwargs.ray_init.runtime_env.env_vars.TROPD_OFFPOLICY_ENABLE="$TROPD_OFFPOLICY_ENABLE" \
        +ray_kwargs.ray_init.runtime_env.env_vars.TROPD_OFFPOLICY_BETA="$TROPD_OFFPOLICY_BETA" \
        +ray_kwargs.ray_init.runtime_env.env_vars.TROPD_OFFPOLICY_MAX_PREFIX_LEN="$TROPD_OFFPOLICY_MAX_PREFIX_LEN" \
        +ray_kwargs.ray_init.runtime_env.env_vars.TROPD_OFFPOLICY_ANNEAL="$TROPD_OFFPOLICY_ANNEAL" \
        +ray_kwargs.ray_init.runtime_env.env_vars.TROPD_OFFPOLICY_ANNEAL_STEPS="$TROPD_OFFPOLICY_ANNEAL_STEPS" \
        +ray_kwargs.ray_init.runtime_env.env_vars.TROPD_OFFPOLICY_STEP="$TROPD_OFFPOLICY_STEP" \
        +ray_kwargs.ray_init.runtime_env.env_vars.TROPD_OFFPOLICY_TEACHER_DO_SAMPLE="$TROPD_OFFPOLICY_TEACHER_DO_SAMPLE" \
        +ray_kwargs.ray_init.runtime_env.env_vars.TROPD_OFFPOLICY_TEACHER_TEMPERATURE="$TROPD_OFFPOLICY_TEACHER_TEMPERATURE" \
        +ray_kwargs.ray_init.runtime_env.env_vars.TROPD_OFFPOLICY_TEACHER_TOP_P="$TROPD_OFFPOLICY_TEACHER_TOP_P" \
        +ray_kwargs.ray_init.runtime_env.env_vars.TROPD_OFFPOLICY_TEACHER_TOP_K="$TROPD_OFFPOLICY_TEACHER_TOP_K" \
        "$@"
